import { TimerTemplate } from '../types';

function calculateTotalDuration(t: {
  prepareSeconds: number;
  workSeconds: number;
  restSeconds: number;
  rounds: number;
  sets: number;
  restBetweenSetsSeconds: number;
  cooldownSeconds: number;
}): number {
  const roundDuration = t.workSeconds + t.restSeconds;
  const setDuration = roundDuration * t.rounds - t.restSeconds;
  const allSets = setDuration * t.sets;
  const betweenSetsRest = t.restBetweenSetsSeconds * Math.max(0, t.sets - 1);
  return t.prepareSeconds + allSets + betweenSetsRest + t.cooldownSeconds;
}

const now = new Date().toISOString();

export const PRESET_TEMPLATES: TimerTemplate[] = [
  {
    id: 'preset-tabata',
    name: 'Tabata Classic',
    type: 'preset',
    category: 'tabata',
    prepareSeconds: 10,
    workSeconds: 20,
    restSeconds: 10,
    rounds: 8,
    sets: 1,
    restBetweenSetsSeconds: 0,
    cooldownSeconds: 0,
    totalDurationSeconds: calculateTotalDuration({ prepareSeconds: 10, workSeconds: 20, restSeconds: 10, rounds: 8, sets: 1, restBetweenSetsSeconds: 0, cooldownSeconds: 0 }),
    colorThemeId: 'vivid',
    iconName: 'zap',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    usageCount: 0,
    lastUsedAt: null,
  },
  {
    id: 'preset-hiit',
    name: 'HIIT Standard',
    type: 'preset',
    category: 'hiit',
    prepareSeconds: 10,
    workSeconds: 30,
    restSeconds: 15,
    rounds: 10,
    sets: 1,
    restBetweenSetsSeconds: 0,
    cooldownSeconds: 30,
    totalDurationSeconds: calculateTotalDuration({ prepareSeconds: 10, workSeconds: 30, restSeconds: 15, rounds: 10, sets: 1, restBetweenSetsSeconds: 0, cooldownSeconds: 30 }),
    colorThemeId: 'sunset',
    iconName: 'flame',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    usageCount: 0,
    lastUsedAt: null,
  },
  {
    id: 'preset-boxing',
    name: 'Boxing 3-min',
    type: 'preset',
    category: 'boxing',
    prepareSeconds: 10,
    workSeconds: 180,
    restSeconds: 60,
    rounds: 12,
    sets: 1,
    restBetweenSetsSeconds: 0,
    cooldownSeconds: 0,
    totalDurationSeconds: calculateTotalDuration({ prepareSeconds: 10, workSeconds: 180, restSeconds: 60, rounds: 12, sets: 1, restBetweenSetsSeconds: 0, cooldownSeconds: 0 }),
    colorThemeId: 'fire',
    iconName: 'swords',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    usageCount: 0,
    lastUsedAt: null,
  },
  {
    id: 'preset-emom',
    name: 'EMOM 10',
    type: 'preset',
    category: 'crossfit',
    prepareSeconds: 10,
    workSeconds: 60,
    restSeconds: 0,
    rounds: 10,
    sets: 1,
    restBetweenSetsSeconds: 0,
    cooldownSeconds: 0,
    totalDurationSeconds: calculateTotalDuration({ prepareSeconds: 10, workSeconds: 60, restSeconds: 0, rounds: 10, sets: 1, restBetweenSetsSeconds: 0, cooldownSeconds: 0 }),
    colorThemeId: 'ocean',
    iconName: 'repeat',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    usageCount: 0,
    lastUsedAt: null,
  },
  {
    id: 'preset-amrap',
    name: 'AMRAP 20',
    type: 'preset',
    category: 'crossfit',
    prepareSeconds: 10,
    workSeconds: 1200,
    restSeconds: 0,
    rounds: 1,
    sets: 1,
    restBetweenSetsSeconds: 0,
    cooldownSeconds: 0,
    totalDurationSeconds: calculateTotalDuration({ prepareSeconds: 10, workSeconds: 1200, restSeconds: 0, rounds: 1, sets: 1, restBetweenSetsSeconds: 0, cooldownSeconds: 0 }),
    colorThemeId: 'forest',
    iconName: 'infinity',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    usageCount: 0,
    lastUsedAt: null,
  },
  {
    id: 'preset-circuit',
    name: 'Circuit Burn',
    type: 'preset',
    category: 'circuit',
    prepareSeconds: 10,
    workSeconds: 45,
    restSeconds: 15,
    rounds: 6,
    sets: 3,
    restBetweenSetsSeconds: 60,
    cooldownSeconds: 30,
    totalDurationSeconds: calculateTotalDuration({ prepareSeconds: 10, workSeconds: 45, restSeconds: 15, rounds: 6, sets: 3, restBetweenSetsSeconds: 60, cooldownSeconds: 30 }),
    colorThemeId: 'neon',
    iconName: 'activity',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    usageCount: 0,
    lastUsedAt: null,
  },
  {
    id: 'preset-stretch',
    name: 'Stretch & Flow',
    type: 'preset',
    category: 'stretching',
    prepareSeconds: 5,
    workSeconds: 30,
    restSeconds: 5,
    rounds: 10,
    sets: 1,
    restBetweenSetsSeconds: 0,
    cooldownSeconds: 0,
    totalDurationSeconds: calculateTotalDuration({ prepareSeconds: 5, workSeconds: 30, restSeconds: 5, rounds: 10, sets: 1, restBetweenSetsSeconds: 0, cooldownSeconds: 0 }),
    colorThemeId: 'midnight',
    iconName: 'wind',
    createdAt: now,
    updatedAt: now,
    isFavorite: false,
    usageCount: 0,
    lastUsedAt: null,
  },
];
